spring:
  datasource:
    url: jdbc:h2:mem:product_db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: p
    driverClassName: org.h2.Driver
  h2:
    console:
      # http://localhost:${PORT}/h2-console
      enabled: true

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.example.product: DEBUG